const SAVE_MODEL = 'SAVE_MODEL';
const SAVING_MODEL = 'SAVING_MODEL';
const SAVED_MODEL = 'SAVED_MODEL';
const FETCHING_MODELS = 'FETCHING_MODELS';
const FETCHED_MODELS = 'FETCHED_MODELS';
const FETCHING_MODEL = 'FETCHING_MODEL';
const FETCHED_MODEL = 'FETCHED_MODEL';
const SELECT_MODEL = 'SELECT_MODEL';
const DESELECT_MODEL = 'DESELECT_MODEL';

module.exports = {
  SAVE_MODEL,
  SAVING_MODEL,
  SAVED_MODEL,
  FETCHING_MODELS,
  FETCHED_MODELS,
  FETCHING_MODEL,
  FETCHED_MODEL,
  SELECT_MODEL,
  DESELECT_MODEL,
}