"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DESELECT_MODEL = exports.SELECT_MODEL = exports.FETCHED_MODEL = exports.FETCHING_MODEL = exports.FETCHED_MODELS = exports.FETCHING_MODELS = exports.SAVED_MODEL = exports.SAVING_MODEL = exports.SAVE_MODEL = void 0;
const SAVE_MODEL = 'SAVE_MODEL';
exports.SAVE_MODEL = SAVE_MODEL;
const SAVING_MODEL = 'SAVING_MODEL';
exports.SAVING_MODEL = SAVING_MODEL;
const SAVED_MODEL = 'SAVED_MODEL';
exports.SAVED_MODEL = SAVED_MODEL;
const FETCHING_MODELS = 'FETCHING_MODELS';
exports.FETCHING_MODELS = FETCHING_MODELS;
const FETCHED_MODELS = 'FETCHED_MODELS';
exports.FETCHED_MODELS = FETCHED_MODELS;
const FETCHING_MODEL = 'FETCHING_MODEL';
exports.FETCHING_MODEL = FETCHING_MODEL;
const FETCHED_MODEL = 'FETCHED_MODEL';
exports.FETCHED_MODEL = FETCHED_MODEL;
const SELECT_MODEL = 'SELECT_MODEL';
exports.SELECT_MODEL = SELECT_MODEL;
const DESELECT_MODEL = 'DESELECT_MODEL';
exports.DESELECT_MODEL = DESELECT_MODEL;